import { Product } from './types/Product';

export const sampleProduct: Product[] = [
  {
    name: 'Nike Victory t-shirt',
    slug: 'Nike Victory t-shirt',
    image: '../images/tshirt2.jpeg',
    category: 'Shirts',
    brand: 'Nike',
    price: 543,
    countInStock: 43,
    description: 'High quality shirt',
    rating: 4.5,
    numReviews: 4,
  },
  {
    name: 'Adidas Fit shirt',
    slug: 'Adidas Fit shirt',
    image: '../images/tshirt8.jpeg',
    category: 'Shirts',
    brand: 'Adidas',
    price: 209,
    countInStock: 33,
    description: 'High quality shirt',
    rating: 4.0,
    numReviews: 10,
  },
  {
    name: 'Lacoste Jeans Pants',
    slug: 'Lacoste Jeans Pants',
    image: '../images/pants4.jpeg',
    category: 'Pants',
    brand: 'Lacoste',
    price: 633,
    countInStock: 22,
    description: 'High quality pants',
    rating: 4.8,
    numReviews: 14,
  },
  {
    name: 'Lacoste Red t-shirt',
    slug: 'Lacoste Red t-shirt',
    image: '../images/tshirt5.jpeg',
    category: 'Shirts',
    brand: 'Lacoste',
    price: 633,
    countInStock: 22,
    description: 'High quality shirt',
    rating: 4.8,
    numReviews: 14,
  },
  {
    name: 'Nike Slim pants',
    slug: 'Nike Slim pants',
    image: '../images/pants3.jpeg',
    category: 'Pants',
    brand: 'Nike',
    price: 243,
    countInStock: 12,
    description: 'High quality pants',
    rating: 4.5,
    numReviews: 8,
  },
  {
    name: 'Nike Slim t-shirt',
    slug: 'Nike Slim t-shirt',
    image: '../images/tshirt4.jpeg',
    category: 'Shirts',
    brand: 'Nike',
    price: 243,
    countInStock: 12,
    description: 'High quality pants',
    rating: 4.5,
    numReviews: 8,
  },
];
