import { Product } from './types/Product';

export const sampleProduct: Product[] = [
  {
    name: 'Nike Slim shirt',
    slug: 'Nike Slim shirt',
    image: '../images/nike_shirt.jpeg',
    category: 'Shirts',
    brand: 'Nike',
    price: 543,
    countInStock: 43,
    description: 'High quality shirt',
    rating: 4.5,
    numReviews: 4,
  },
  {
    name: 'Adidas Fit shirt',
    slug: 'Adidas Fit shirt',
    image: '../images/adidas_shirt.jpeg',
    category: 'Shirts',
    brand: 'Adidas',
    price: 209,
    countInStock: 33,
    description: 'High quality shirt',
    rating: 4.0,
    numReviews: 10,
  },
  {
    name: 'Lacoste Sport Pants',
    slug: 'Lacoste Sport Pants',
    image: '../images/lacoste_sport_pants.jpeg',
    category: 'Pants',
    brand: 'Lacoste',
    price: 633,
    countInStock: 22,
    description: 'High quality pants',
    rating: 4.8,
    numReviews: 14,
  },
  {
    name: 'Lacoste white t-shirt',
    slug: 'Lacoste white t-shirt',
    image: '../images/lacoste_tshirt.jpeg',
    category: 'shirts',
    brand: 'Lacoste',
    price: 633,
    countInStock: 22,
    description: 'High quality shirt',
    rating: 4.8,
    numReviews: 14,
  },
  {
    name: 'Nike Slim pants',
    slug: 'Nike Slim pants',
    image: '../images/nike_slim_pants.jpeg',
    category: 'Pants',
    brand: 'Nike',
    price: 243,
    countInStock: 12,
    description: 'High quality pants',
    rating: 4.5,
    numReviews: 8,
  },
];
